project 'NewAutoLayout.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewAutoLayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FDStackView', '~> 1.0'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  
  target 'NewAutoLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewAutoLayoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
